version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      PGHOST: ${PGHOST}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
      DJANGO_SECRET_KEY: PASTE_YOUR_KEY_HERE
      DJANGO_DEBUG: "False"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,backend,192.168.8.206,nfcstore.lat"
      CORS_ALLOWED_ORIGINS: "http://localhost:5173,http://127.0.0.1:5173,http://192.168.8.206:5173,https://nfcstore.lat"
      CSRF_TRUSTED_ORIGINS: "http://localhost:5173,http://127.0.0.1:5173,http://192.168.8.206:5173,https://nfcstore.lat"
    volumes:
      - ./backend:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    environment:
      VITE_API_URL: ""
      DJANGO_DEBUG: ${DJANGO_DEBUG}

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token eyJhIjoiNzdkYjBjZDc0NDRmNDU4OGU2YmU5Y2FhZDQ0NGMwYjMiLCJ0IjoiZjU4MDNjNmMtZDVhMS00ZDQ1LWFhNDItODg4MzMzMmFkOWVjIiwicyI6Ik16VmxOelJrTmpBdFpETXlZeTAwWWpBMUxXSmpOVGN0TjJKbFpEYzRPR0UzWmpoaiJ9
